---
title: "ICIS Heren reports - clear code"
author: "Katerina Krizova"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: false
    fig_caption: true
  fontsize: 11pt
  geometry: margin=1in
---

# HARVEST

-- comlete process of ICIS report harvesting
-- creates two result files:
    ICISHeren_harvestedReports_DA_WE_MA.xlsx 
    ICISHeren_harvestedReports_complete.xlsx

```{r, echo=FALSE}

# PACKAGES, SETTINGS, PATHS, FUNCTIONS =========================================

require(tidyverse)
require(openxlsx)

Sys.setlocale("LC_TIME", "C")

path_in <- "C:/Users/krizova/Documents/R/ICISHeren/csv_oper/"
path_bu <- "C:/Users/krizova/Documents/R/ICISHeren/xlsx_results/d-1_backup/"
path_out <- "C:/Users/krizova/Documents/R/ICISHeren/xlsx_results/"

append_to_excel <- function(df, file_path, sheet = 1) {
  library(openxlsx)
  
  if (file.exists(file_path)) {
    wb <- loadWorkbook(file_path)
    existing_data <- read.xlsx(file_path, sheet = sheet)
    next_row <- nrow(existing_data) + 2  # +1 for header, +1 for next row
  } else {
    wb <- createWorkbook()
    addWorksheet(wb, sheetName = ifelse(is.numeric(sheet), "Sheet1", sheet))
    next_row <- 1
  }
  writeData(wb, sheet = sheet, x = df, startRow = next_row,
            colNames = (next_row == 1), na.string = "")
  # setColWidths(wb, sheet = "Sheet1", cols = 1:ncol(df), widths = "auto")
  freezePane(wb, sheet = "Sheet1", firstActiveRow = 2)
  addStyle(wb, "Sheet1", createStyle(textDecoration = "bold"), rows = 1, cols = 1:100, gridExpand = TRUE)
  saveWorkbook(wb, file = file_path, overwrite = TRUE)
}

# COPY LATEST FILES FROM X TO C ================================================

Ltrh <- c("TTF", "THE", "VTP") 
for (i in Ltrh) {
  files <- list.files("X:/ICIS_Heren/", pattern = paste0(i, ".csv"), full.names = T) 
  if (length(files) > 0) {
    info <- file.info(files)
    newest_file <- rownames(info)[which.max(info$mtime)]
    file.copy(from = newest_file,
          to = path_in)
  }
} 

rm(info)

# LOOP READ AND CLEAR THREE SEPARATE FILES =====================================

Ltrh <- c("TTF", "THE", "VTP")
for (i in Ltrh) {
  files <- list.files(path_in, pattern = paste0(i, ".csv"), full.names = T) 
  if (length(files) > 0) {
    info <- file.info(files)
    newest_file <- rownames(info)[which.max(info$mtime)]
    df <- read.csv(newest_file, header = TRUE, sep = ",") %>% 
      filter(str_detect(Name, "^Natural Gas")) %>% 
      mutate(publ = as.Date(Date, format = "%d %b %Y"),
             weekday = weekdays(publ),
             Den = case_when(weekday == "Monday" ~ "po",
                             weekday == "Tuesday" ~ "ut",
                             weekday == "Wednesday" ~ "st",
                             weekday == "Thursday" ~ "ct",
                             weekday == "Friday" ~ "pa",
                             weekday == "Saturday" ~ "so",
                             weekday == "Sunday" ~ "ne"),
             Indicator = str_remove(Name, " TTF| THE| Czech Republic"),
             deli = case_when(Den == "pa" & Indicator == "Natural Gas Day-ahead" ~ publ  + 3, 
                              Den == "pa" & Indicator == "Natural Gas Weekend+0" ~ publ  + 1,
                              TRUE ~ publ + 1),
             deli_day = case_when(Den == "pa" & Indicator == "Natural Gas Day-ahead" ~ "po", 
                                  Den == "po" & Indicator == "Natural Gas Day-ahead" ~ "ut",
                                  Den == "ut" & Indicator == "Natural Gas Day-ahead" ~ "st",
                                  Den == "st" & Indicator == "Natural Gas Day-ahead" ~ "ct",
                                  Den == "ct" & Indicator == "Natural Gas Day-ahead" ~ "pa",
                                  Den == "pa" & Indicator == "Natural Gas Weekend+0" ~ "so+ne",
                                  TRUE ~ NA),
             empty_col = "")
    print(newest_file)
    rm(info)
    rm(newest_file)
  } else {
    warning("Not the robots you're looking for.")
  }
  if (i == "TTF"){
    df <- df %>% select("Publication day" = Den, publ, deli, "Delivery day" = deli_day, Indicator, Period, "TTF Bid" = Bid, "TTF Offer" = Offer, "TTF Mid" = Mid.Price, "*" = empty_col)
    assign("ttf", df)
  } else if (i == "THE"){
    df <- df %>% select(Indicator, "THE Bid" = Bid, "THE Offer" = Offer, "THE Mid" = Mid.Price, "**" = empty_col) 
    assign("the", df)
  } else if (i == "VTP"){
    df <- df %>% select(Indicator, "CZ-VTP Bid" = Bid, "CZ-VTP Offer" = Offer, "CZ-VTP Mid" = Mid.Price, "***" = empty_col) 
    assign("vtp", df)
  } else {
    warning("I have a bad feeling about this.")
  }
  rm(df)
  rm(i)
  rm(files)
} 

# CHECK NUMBER OF ROWS =========================================================

print(paste("TTF has more rows than TTF and VTP:", 
            nrow(ttf) > nrow(the) & nrow(ttf) > nrow(vtp))) # chceme TRUE

# CONSOLIDATE THREE DF TO ONE

cons <- left_join(ttf, the, by = "Indicator") %>%
  left_join(vtp, by = "Indicator") %>%
  mutate(across(c('TTF Bid', 'TTF Offer', 'TTF Mid',
                  'THE Bid', 'THE Offer', 'THE Mid',
                  'CZ-VTP Bid', 'CZ-VTP Offer', 'CZ-VTP Mid'), as.numeric)) %>% 
   mutate(across(where(is.character), ~ replace(., is.na(.), "")))

# RESULT 1: DA, WE, MA =========================================================

da <- cons %>% 
  filter(ifelse(`Publication day` == "pa", Indicator %in% c("Natural Gas Weekend+0", "Natural Gas Day-ahead"), Indicator == "Natural Gas Day-ahead")) %>% 
  filter(str_detect(Indicator, "^Natural"))
names(da) <- ifelse(grepl("Bid|Offer|Mid", names(da)), paste0("(d) ", names(da)), names(da))

mo <- cons %>% 
  filter(str_detect(Indicator, "Natural Gas Month.1")) %>%  # z nejakeho duvodu chce cely nazev. regex nefunguje
  select(-'Publication day', -deli, -publ, -'Delivery day')
names(mo) <- ifelse(grepl("Indicator|Period|Bid|Offer|Mid", names(mo)), paste0("(m) ", names(mo)), names(mo))
names(mo) <- ifelse(grepl("\\*+", names(mo)), paste0("***", names(mo)), names(mo))

lines <- cbind(da, mo) %>% 
  select(-`******`)

day <- unique(lines$`Publication day`)

if (day == "pa"){
  lines <- rbind(lines, lines[rep(2, 1), ])
  # lines$deli[lines$Indicator == "Natural Gas Day-ahead"] <- lines$publ+3
  lines$deli[nrow(lines)] <- lines$publ+2
  lines <- lines[order(lines$deli), ]
} else{
  lines$deli <- lines$publ+1
}

dawemo <- lines %>% 
  mutate('Publication date' = format(publ, "%d.%m.%Y"),
         'Delivery date' = format(deli, "%d.%m.%Y")) %>% 
  select(-publ, -deli) %>% 
  relocate('Publication date', 'Delivery date', .after = `Publication day`)

rm(lines)

# RESULT 2: COMPLETE ICIS ======================================================

icis <- cons %>% 
 mutate(`THE/TTF` = `THE Mid`-`TTF Mid`,
         `CZ-VTP/TTF` = `CZ-VTP Mid`-`TTF Mid`,
         `CZ-VTP/THE` = `CZ-VTP Mid`-`THE Mid`,
         `Publication date` = format(publ, "%d.%m.%Y"),
         `Delivery date` = ifelse(str_detect(Indicator, "Day-ahead"), format(deli, "%d.%m.%Y"), "")) %>% 
  select(-publ, -deli) %>% 
  relocate(`Publication date`, `Delivery date`, .after = `Publication day`)

append_icis <- paste0(path_out, "ICISHeren_harvestedReports_complete.xlsx")
append_to_excel(icis, append_icis)

# EXPORT TO EXCEL ==============================================================

# 1st round
# wb <- createWorkbook()
# addWorksheet(wb, "Sheet1")
# writeData(wb, sheet = "Sheet1", x = dawemo)
# saveWorkbook(wb, paste0(path_out, "ICISHeren_harvestedReports_DA_WE_MA.xlsx"))

# every other round - append
wb <- loadWorkbook(paste0(path_bu, "ICISHeren_harvestedReports_DA_WE_MA.xlsx"))
existing_data <- read.xlsx(wb, sheet = "Sheet1")
new_row <- dawemo
start_row <- nrow(existing_data) + 2  # +2 to account for header row
writeData(wb, sheet = "Sheet1", x = new_row, 
          startRow = start_row, colNames = FALSE, na.string = "")

# style and save
style_DD <- createStyle(fgFill = "darkseagreen1")
style_TTF <- createStyle(fgFill = "powderblue")
style_THE <- createStyle(fgFill = "palegoldenrod")
style_VTP <- createStyle(fgFill = "mistyrose2")
addStyle(wb, sheet = "Sheet1", style = style_DD, cols = 3, rows = 1:1000, gridExpand = TRUE)
addStyle(wb, sheet = "Sheet1", style = style_TTF, cols = 7:9, rows = 1:1000, gridExpand = TRUE)
addStyle(wb, sheet = "Sheet1", style = style_TTF, cols = 21:23, rows = 1:1000, gridExpand = TRUE)
addStyle(wb, sheet = "Sheet1", style = style_THE, cols = 11:13, rows = 1:1000, gridExpand = TRUE)
addStyle(wb, sheet = "Sheet1", style = style_THE, cols = 25:27, rows = 1:1000, gridExpand = TRUE)
addStyle(wb, sheet = "Sheet1", style = style_VTP, cols = 15:17, rows = 1:1000, gridExpand = TRUE)
addStyle(wb, sheet = "Sheet1", style = style_VTP, cols = 29:31, rows = 1:1000, gridExpand = TRUE)
addStyle(wb, "Sheet1", createStyle(textDecoration = "bold"), rows = 1, cols = 1:100, gridExpand = TRUE)
freezePane(wb, sheet = "Sheet1", firstActiveRow = 2)
# setColWidths(wb, sheet = "Sheet1", cols = 1:100, widths = "auto") 
saveWorkbook(wb, paste0(path_out, "ICISHeren_harvestedReports_DA_WE_MA.xlsx"), overwrite = T)

print(paste0("ICIS Heren report for ", dawemo$`Delivery date` , " completed."))

```

# BACK-UP

-- optional
-- execute when satisfied with the result
-- creates back-up copy for the day

```{r}
# DELETE OPER CSV ==============================================================

unlink(paste0(path_in, "*"), recursive = FALSE)

# PERSONAL BACKUP COPY =================== uncomment ===========================

file.copy(from = paste0(path_out, "ICISHeren_harvestedReports_DA_WE_MA.xlsx"),
          to = path_bu,
          overwrite = TRUE)
file.copy(from = paste0(path_out, "ICISHeren_harvestedReports_complete.xlsx"),
          to = path_bu,
          overwrite = TRUE)

# COPY TO NAKUP ========================== uncomment ===========================

file.copy(from = paste0(path_out, "ICISHeren_harvestedReports_DA_WE_MA.xlsx"),
          to = "X:/Nakup _ NEW/Pracovni/sklizene ICIS Heren/ICISHeren_harvestedReports_DA_WE_MA.xlsx",
          overwrite = TRUE)
file.copy(from = paste0(path_out, "ICISHeren_harvestedReports_complete.xlsx"),
          to = "X:/Nakup _ NEW/Pracovni/sklizene ICIS Heren/ICISHeren_harvestedReports_complete.xlsx",
          overwrite = TRUE)

# CLEAR ENVIRONMENT

rm(list=ls())

```
```

